userName: username
accessKey: password

projectName: Smart Test Selection Impact Analysis Demo Project
buildName: Smart Test Selection Impact Analysis Demo Build 
buildIdentifier: '#${BUILD_NUMBER}'
framework: pytest

testObservability: true
automation: false
browserstackLocal: false
platforms:
  - os: Windows
    osVersion: 11
    browserName: Chrome
    browserVersion: latest

source: pytest-browserstack:local-sdk:v1.0
debug: true
logLevel: debug

testOrchestrationOptions:
  runSmartSelection:
    enabled: true
    mode: 'relevantFirst'
    source: 'test-selection.json'
