userName: username
accessKey: password

projectName: Sample_Web_App
buildName: local-pytest-build
buildIdentifier: '#${BUILD_NUMBER}'
framework: pytest

testObservability: true
automation: false
browserstackLocal: false

source: pytest-browserstack:local-sdk:v1.0
debug: true
logLevel: debug

testOrchestrationOptions:
  runSmartSelection:
    enabled: true
    mode: 'relevantFirst'
    source: 'test-selection.json'
